/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_jni_JniMain */

#ifndef _Included_com_test_jni_JniMain
#define _Included_com_test_jni_JniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * JNI 的函数声明，供Java调用
 * Class:     com_test_jni_JniMain
 * Method:    fibonacci
 * Signature: (I)I
 */
JNIEXPORT jint
JNICALL Java_com_test_jni_JniMain_fibonacci
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif

// 头文件函数声明；该函数通过C文件具体实现
unsigned int Fibonacci(unsigned int n);

#endif //_Included_com_test_jni_JniMain
